### ISSUE TITLE
Memory leaks on every success call of the `IbSendInit `

### ISSUE THREAD

**Issue by Pennywise007** [Chaoses-Ib/IbInputSimulator#15]
When user receives Send::Error::Success from IbSendInit function it means that [send](https://github.com/Chaoses-Ib/IbInputSimulator/blob/develop/Simulator/source/dllmain.cpp#L27) variable has been initialized with any of the 'SendTypes'. But when we stop the program it calls IbSendDestroy, or in my case I can call this function several times to reinit dll with another driver with calling IbSendDestroy before Init.
IbSendDestroy checks if `send` variable is not empty and calls [send.release()](https://github.com/Chaoses-Ib/IbInputSimulator/blob/develop/Simulator/source/dllmain.cpp#L168). Which leads to the memory leak. I guess you call it because you got problems with inheritance and if you simply replace this line with `main::send.reset()` it will fail to destroy objects.
It can be also resolved by adding default destructor to Base class like:
`virtual ~Base() = default;`

**Comment by Pennywise007** [comment]
By the way, why do you need double inheritance from Base in [class Razer](https://github.com/Chaoses-Ib/IbInputSimulator/blob/develop/Simulator/include/IbInputSimulator/SendTypes/Razer.hpp#L6) and in [class Logitech](https://github.com/Chaoses-Ib/IbInputSimulator/blob/develop/Simulator/include/IbInputSimulator/SendTypes/Logitech.hpp#L232C5-L232C19)? They both are inherited from the VirtualKeyStates who already has inheritance from Base.
You can drop this virtual inheritance of this classes from Base and just inherit from VirtualKeyState

**Comment by Chaoses-Ib** [comment]
> IbSendDestroy checks if `send` variable is not empty and calls [send.release()](https://github.com/Chaoses-Ib/IbInputSimulator/blob/develop/Simulator/source/dllmain.cpp?rgh-link-date=2024-05-03T23%3A31%3A53Z#L168). Which leads to the memory leak. I guess you call it because you got problems with inheritance and if you simply replace this line with `main::send.reset()` it will fail to destroy objects.

It's written a long time ago and I'm not sure why it's that, probably it's just that I misunderstood what `release()` is and thought it's releasing the object rather than leaking it.

> By the way, why do you need double inheritance from Base in [class Razer](https://github.com/Chaoses-Ib/IbInputSimulator/blob/develop/Simulator/include/IbInputSimulator/SendTypes/Razer.hpp?rgh-link-date=2024-05-03T23%3A45%3A29Z#L6) and in [class Logitech](https://github.com/Chaoses-Ib/IbInputSimulator/blob/develop/Simulator/include/IbInputSimulator/SendTypes/Logitech.hpp?rgh-link-date=2024-05-03T23%3A45%3A29Z#L232C5-L232C19)? They both are inherited from the VirtualKeyStates who already has inheritance from Base.

`VirtualKeyStates` was added after `Base`. The reason why I kept both of them is probably I thought it's more consistent and clearer to read.

Thanks for your PR.
