### ISSUE TITLE
示例程序无法正常工作

### ISSUE THREAD

**Issue by wajunye** [Chaoses-Ib/IbInputSimulator#4]
使用 AHK v1 这个示例程序时，程序没有反应，没有任何动作也没有报错。

**Comment by Chaoses-Ib** [comment]
你安装的是哪个驱动？版本是多少？

**Comment by wtx3215860** [comment]
您好，使用 IbAhkSendLib\v1\test\mode 0这个示例程序的时候，IbSend("{Click 5, 5, down}{click 150, 50, up}")这条命令不执行。

**Comment by wtx3215860** [comment]
您好，使用 IbASendLib\v1\test\mode 0 这个示例程序的时候，IbSend({Click 5, 5, down}{click 150, 50, up}")这条命令不执行。

**Comment by Chaoses-Ib** [comment]
> 您好，使用 IbASendLib\v1\test\mode 0 这个示例程序的时候，IbSend({Click 5, 5, down}{click 150, 50, up}")这条命令不执行。

你安装的是哪个驱动？版本是多少？

**Comment by wtx3215860** [comment]
> > 您好，使用 IbASendLib\v1\test\0 这个示例程序的时候，IbSend({Click 5, 5, down}{click 150, 50, up}")这个命令命令不执行。
> 
> 你安装的是哪个驱动版本？版本是多少？

我安装的是Logitech G HUB 2022.8.306864版本的罗技驱动，使用的是AutoHotkey_1.1.34.02版本的AHK，只有IbSend({Click, }操作鼠标的命令不能执行，操作键盘的命令是可以准确执行的。

**Comment by wtx3215860** [comment]
> > 您好，使用 IbASendLib\v1\test\mode 0 这个示例程序的时候，IbSend({Click 5, 5, down}{click 150, 50, up}")这条命令不执行。
> 
> 你安装的是哪个驱动？版本是多少？

请问是否是我Logitech G HUB版本太新了，如果是的话请问使用哪个版本的Logitech G HUB驱动才能使用IbSend({Click, }命令。

**Comment by Chaoses-Ib** [comment]
G HUB 没有离线安装包，在线安装包只能安装最新版。目前我已经在 G HUB 下复现了，你可以等我修复或者先使用 [LGS v9.02.65](https://github.com/Chaoses-Ib/IbInputSimulator/releases/tag/v0.1)。

**Comment by wtx3215860** [comment]
> G HUB 没有离线安装包，在线安装包只能安装最新版。目前我已经在 G HUB 下复现了，你可以等我修复或者先使用 [LGS v9.02.65](https://github.com/Chaoses-Ib/IbInputSimulator/releases/tag/v0.1)。

好的！谢谢你！

**Comment by Chaoses-Ib** [comment]
最新版的 G HUB 和 LGS 似乎直接阉割了部分鼠标功能。驱动不再支持鼠标按键或移动，G HUB 和 LGS 的 Lua 宏会使用 SendInput 而不是驱动来实现被阉割的功能。
